-- MySQL Script generated by MySQL Workbench
-- Sat 27 Mar 2021 02:21:57 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trabBD56
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `trabBD56` ;

-- -----------------------------------------------------
-- Schema trabBD56
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabBD56` ;
USE `trabBD56` ;

-- -----------------------------------------------------
-- Table `trabBD56`.`UnidadeFederaçao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`UnidadeFederaçao` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`UnidadeFederaçao` (
  `siglaUF` VARCHAR(5) NOT NULL,
  `nomeUF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`siglaUF`),
  UNIQUE INDEX `idUnidadeFederaçao_UNIQUE` (`siglaUF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabBD56`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`Cidade` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`Cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nomeCidade` VARCHAR(45) NOT NULL,
  `UnidadeFederaçao_siglaUF` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idCidade`),
  UNIQUE INDEX `idCidade_UNIQUE` (`idCidade` ASC) VISIBLE,
  INDEX `fk_Cidade_UnidadeFederaçao1_idx` (`UnidadeFederaçao_siglaUF` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_UnidadeFederaçao1`
    FOREIGN KEY (`UnidadeFederaçao_siglaUF`)
    REFERENCES `trabBD56`.`UnidadeFederaçao` (`siglaUF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabBD56`.`Bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`Bairro` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`Bairro` (
  `idBairro` INT NOT NULL AUTO_INCREMENT,
  `nomeBairro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBairro`),
  UNIQUE INDEX `idBairro_UNIQUE` (`idBairro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabBD56`.`TipoLogradouro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`TipoLogradouro` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`TipoLogradouro` (
  `siglaTipoLogradouro` INT NOT NULL,
  `nomeLogradouro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`siglaTipoLogradouro`),
  UNIQUE INDEX `siglaTipoLogradouro_UNIQUE` (`siglaTipoLogradouro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabBD56`.`Logradouro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`Logradouro` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`Logradouro` (
  `idLogradouro` INT NOT NULL AUTO_INCREMENT,
  `nomeLogradouro` VARCHAR(45) NOT NULL,
  `TipoLogradouro_siglaTipoLogradouro` INT NOT NULL,
  PRIMARY KEY (`idLogradouro`),
  UNIQUE INDEX `idLogradouro_UNIQUE` (`idLogradouro` ASC) VISIBLE,
  INDEX `fk_Logradouro_TipoLogradouro1_idx` (`TipoLogradouro_siglaTipoLogradouro` ASC) VISIBLE,
  CONSTRAINT `fk_Logradouro_TipoLogradouro1`
    FOREIGN KEY (`TipoLogradouro_siglaTipoLogradouro`)
    REFERENCES `trabBD56`.`TipoLogradouro` (`siglaTipoLogradouro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabBD56`.`Endereço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`Endereço` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`Endereço` (
  `idEndereço` INT NOT NULL AUTO_INCREMENT,
  `CEP` VARCHAR(45) NOT NULL,
  `Cidade_idCidade` INT NOT NULL,
  `Bairro_idBairro` INT NOT NULL,
  `Logradouro_idLogradouro` INT NOT NULL,
  PRIMARY KEY (`idEndereço`),
  UNIQUE INDEX `idEndereço_UNIQUE` (`idEndereço` ASC) VISIBLE,
  INDEX `fk_Endereço_Cidade1_idx` (`Cidade_idCidade` ASC) VISIBLE,
  INDEX `fk_Endereço_Bairro1_idx` (`Bairro_idBairro` ASC) VISIBLE,
  INDEX `fk_Endereço_Logradouro1_idx` (`Logradouro_idLogradouro` ASC) VISIBLE,
  CONSTRAINT `fk_Endereço_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `trabBD56`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereço_Bairro1`
    FOREIGN KEY (`Bairro_idBairro`)
    REFERENCES `trabBD56`.`Bairro` (`idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereço_Logradouro1`
    FOREIGN KEY (`Logradouro_idLogradouro`)
    REFERENCES `trabBD56`.`Logradouro` (`idLogradouro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabBD56`.`Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`Paciente` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Nascimento` DATE NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `estadoCivil` VARCHAR(45) NOT NULL,
  `docIdentidade` VARCHAR(45) NOT NULL,
  `Endereço_idEndereço` INT NOT NULL,
  `numeroEndereço` INT NOT NULL,
  `complementoEndereço` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPaciente`, `Endereço_idEndereço`),
  UNIQUE INDEX `idPaciente_UNIQUE` (`idPaciente` ASC) VISIBLE,
  INDEX `fk_Paciente_Endereço1_idx` (`Endereço_idEndereço` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_Endereço1`
    FOREIGN KEY (`Endereço_idEndereço`)
    REFERENCES `trabBD56`.`Endereço` (`idEndereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabBD56`.`Medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`Medico` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`Medico` (
  `idMedico` INT NOT NULL AUTO_INCREMENT,
  `nomeMedico` VARCHAR(45) NOT NULL,
  `crmMedico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMedico`),
  UNIQUE INDEX `idMedico_UNIQUE` (`idMedico` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabBD56`.`Diagnostico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`Diagnostico` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`Diagnostico` (
  `idDiagnostico` INT NOT NULL AUTO_INCREMENT,
  `Diagnostico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDiagnostico`),
  UNIQUE INDEX `idDiagnostico_UNIQUE` (`idDiagnostico` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabBD56`.`Consulta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`Consulta` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`Consulta` (
  `idConsulta` INT NOT NULL AUTO_INCREMENT,
  `dataConsulta` DATE NOT NULL,
  `obsDiagnostico` VARCHAR(45) NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Medico_idMedico` INT NOT NULL,
  `Diagnostico_idDiagnostico` INT NOT NULL,
  PRIMARY KEY (`idConsulta`, `Paciente_idPaciente`, `Medico_idMedico`, `Diagnostico_idDiagnostico`),
  UNIQUE INDEX `idConsulta_UNIQUE` (`idConsulta` ASC) VISIBLE,
  INDEX `fk_Consulta_Paciente_idx` (`Paciente_idPaciente` ASC) VISIBLE,
  INDEX `fk_Consulta_Medico1_idx` (`Medico_idMedico` ASC) VISIBLE,
  INDEX `fk_Consulta_Diagnostico1_idx` (`Diagnostico_idDiagnostico` ASC) VISIBLE,
  CONSTRAINT `fk_Consulta_Paciente`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `trabBD56`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Medico1`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `trabBD56`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Diagnostico1`
    FOREIGN KEY (`Diagnostico_idDiagnostico`)
    REFERENCES `trabBD56`.`Diagnostico` (`idDiagnostico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabBD56`.`TipoExame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`TipoExame` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`TipoExame` (
  `idTipoExame` INT NOT NULL AUTO_INCREMENT,
  `nomeTipoExame` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoExame`),
  UNIQUE INDEX `idTipoExame_UNIQUE` (`idTipoExame` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabBD56`.`Exames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`Exames` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`Exames` (
  `idExames` INT NOT NULL AUTO_INCREMENT,
  `dataExame` DATE NOT NULL,
  `Consulta_idConsulta` INT NOT NULL,
  `Consulta_Paciente_idPaciente` INT NOT NULL,
  `TipoExame_idTipoExame` INT NOT NULL,
  PRIMARY KEY (`idExames`, `Consulta_idConsulta`, `Consulta_Paciente_idPaciente`, `TipoExame_idTipoExame`),
  UNIQUE INDEX `idExames_UNIQUE` (`idExames` ASC) VISIBLE,
  INDEX `fk_Exames_Consulta1_idx` (`Consulta_idConsulta` ASC, `Consulta_Paciente_idPaciente` ASC) VISIBLE,
  INDEX `fk_Exames_TipoExame1_idx` (`TipoExame_idTipoExame` ASC) VISIBLE,
  CONSTRAINT `fk_Exames_Consulta1`
    FOREIGN KEY (`Consulta_idConsulta` , `Consulta_Paciente_idPaciente`)
    REFERENCES `trabBD56`.`Consulta` (`idConsulta` , `Paciente_idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exames_TipoExame1`
    FOREIGN KEY (`TipoExame_idTipoExame`)
    REFERENCES `trabBD56`.`TipoExame` (`idTipoExame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabBD56`.`DDI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`DDI` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`DDI` (
  `numDDI` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numDDI`),
  UNIQUE INDEX `numDDI_UNIQUE` (`numDDI` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabBD56`.`DDD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`DDD` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`DDD` (
  `numDDD` VARCHAR(45) NOT NULL,
  `DDI_numDDI` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numDDD`),
  UNIQUE INDEX `numDDD_UNIQUE` (`numDDD` ASC) VISIBLE,
  INDEX `fk_DDD_DDI1_idx` (`DDI_numDDI` ASC) VISIBLE,
  CONSTRAINT `fk_DDD_DDI1`
    FOREIGN KEY (`DDI_numDDI`)
    REFERENCES `trabBD56`.`DDI` (`numDDI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabBD56`.`Telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`Telefone` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`Telefone` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT,
  `numTelefone` VARCHAR(45) NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `DDD_numDDD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTelefone`, `Paciente_idPaciente`),
  UNIQUE INDEX `idTelefone_UNIQUE` (`idTelefone` ASC) VISIBLE,
  INDEX `fk_Telefone_Paciente1_idx` (`Paciente_idPaciente` ASC) VISIBLE,
  INDEX `fk_Telefone_DDD1_idx` (`DDD_numDDD` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `trabBD56`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_DDD1`
    FOREIGN KEY (`DDD_numDDD`)
    REFERENCES `trabBD56`.`DDD` (`numDDD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabBD56`.`E-Mail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabBD56`.`E-Mail` ;

CREATE TABLE IF NOT EXISTS `trabBD56`.`E-Mail` (
  `idEmail` INT NOT NULL AUTO_INCREMENT,
  `E-Mail` VARCHAR(45) NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`idEmail`, `Paciente_idPaciente`),
  UNIQUE INDEX `idEmail_UNIQUE` (`idEmail` ASC) VISIBLE,
  INDEX `fk_E-Mail_Paciente1_idx` (`Paciente_idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_E-Mail_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `trabBD56`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `trabBD56`.`UnidadeFederaçao`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`UnidadeFederaçao` (`siglaUF`, `nomeUF`) VALUES ('PR', 'Parana');

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabBD56`.`Cidade`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`Cidade` (`idCidade`, `nomeCidade`, `UnidadeFederaçao_siglaUF`) VALUES (1, 'Foz do Iguacu', 'PR');

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabBD56`.`Bairro`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`Bairro` (`idBairro`, `nomeBairro`) VALUES (1, 'Centro');

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabBD56`.`TipoLogradouro`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`TipoLogradouro` (`siglaTipoLogradouro`, `nomeLogradouro`) VALUES (1, 'Rua');

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabBD56`.`Logradouro`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`Logradouro` (`idLogradouro`, `nomeLogradouro`, `TipoLogradouro_siglaTipoLogradouro`) VALUES (1, 'Santos Dummont', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabBD56`.`Endereço`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`Endereço` (`idEndereço`, `CEP`, `Cidade_idCidade`, `Bairro_idBairro`, `Logradouro_idLogradouro`) VALUES (1, '85858585', 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabBD56`.`Paciente`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`Paciente` (`idPaciente`, `Nome`, `Nascimento`, `Sexo`, `estadoCivil`, `docIdentidade`, `Endereço_idEndereço`, `numeroEndereço`, `complementoEndereço`) VALUES (1, 'leo', '1998-08-19', 'M', 'solteiro', '1239182', 1, 123, 'aee');

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabBD56`.`Medico`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`Medico` (`idMedico`, `nomeMedico`, `crmMedico`) VALUES (1, 'Enzo', '0000001');

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabBD56`.`Diagnostico`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`Diagnostico` (`idDiagnostico`, `Diagnostico`) VALUES (1, 'morreu');

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabBD56`.`Consulta`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`Consulta` (`idConsulta`, `dataConsulta`, `obsDiagnostico`, `Paciente_idPaciente`, `Medico_idMedico`, `Diagnostico_idDiagnostico`) VALUES (1, '2010-12-31', 'negligencia medica', 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabBD56`.`TipoExame`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`TipoExame` (`idTipoExame`, `nomeTipoExame`) VALUES (1, 'cardiovascular');

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabBD56`.`Exames`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`Exames` (`idExames`, `dataExame`, `Consulta_idConsulta`, `Consulta_Paciente_idPaciente`, `TipoExame_idTipoExame`) VALUES (1, '2012-12-30', 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabBD56`.`DDI`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`DDI` (`numDDI`) VALUES ('55');

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabBD56`.`DDD`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`DDD` (`numDDD`, `DDI_numDDI`) VALUES ('45', '55');

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabBD56`.`Telefone`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`Telefone` (`idTelefone`, `numTelefone`, `Paciente_idPaciente`, `DDD_numDDD`) VALUES (1, '99999999', 1, '45');

COMMIT;


-- -----------------------------------------------------
-- Data for table `trabBD56`.`E-Mail`
-- -----------------------------------------------------
START TRANSACTION;
USE `trabBD56`;
INSERT INTO `trabBD56`.`E-Mail` (`idEmail`, `E-Mail`, `Paciente_idPaciente`) VALUES (1, 'bruno@gmail.com', 1);

COMMIT;

